#UPDATED: 2024-Jun-28 Experimental Smoothy v3.1
#SUPER-IMPORTANT: Shadows is best in Low and Distance vision in High or less NOT use MAX, disable V-SYNC
#IMPORTANT NOTE: PLEASE DONT TEST PERFOMANCE IN DALARAN, IS A HOLY ***** BAD OPTMIZAED
d3d9.maxFrameRate = 200 # Set manually for limit the Max FPS
#dxvk.hud = fps # REMOVE THIS LINE FOR HIDE FPS HUD or write # for comment
d3d9.maxFrameLatency = 4
d3d9.numBackBuffers = 0 # // I GET MORE FPS IN 0 a mayor numero mayor calidad menos rendimiento
d3d9.presentInterval = 0 # Disable Vsync in 0
d3d9.tearFree = Auto # Vsync replace fuction  // I GET MORE FPS IN False
d3d9.maxAvailableMemory = 1000 # CHANGE IT FOR YOU RAM Size in MB
d3d9.evictManagedOnUnlock = True # forzar la liberación de la memoria utilizada por los recursos de la GPU después de que se desbloqueen en el juego
d3d9.allowDiscard = True # permitir que DXVK deseche los recursos de la GPU que ya no son necesarios
dxvk.enableAsync = True # It option only work in Async Version
dxvk.numCompilerThreads = 0 # CHANGE IT by your threads of CPU <----------------------
dxvk.numAsyncThreads = 0 # 0 is Automatic || It option only work in Async Version
#d3d9.customDeviceId = 0091
#d3d9.customVendorId = 10de
d3d9.samplerAnisotropy = 0
d3d9.invariantPosition = False # New bugs xD
d3d9.memoryTrackTest = True # Get memory values
d3d9.noExplicitFrontBuffer = True # deshabilitar el búfer frontal


# New patches
d3d9.strictConstantCopies = False # Only for GPU users with good GPU RTX >= 1060 or 1070 maybe if you use APU set in False
d3d9.lenientClear = True # Permite una limpieza menos riguroza = More performance
dxvk.maxChunkSize = 0 # 128 or 256 MiB for slow APU like Intel(R) HD Graphics 620
d3d9.longMad = False  # Change to True for try get more perfomance only enable if try use z-pass

############################## 
d3d9.floatEmulation = Auto # New Thing
# Supported values:
# - True: Use a faster but less accurate approach. Good enough for most games
# - False: Disable float emulation completely
# - Strict: Use a slower but more correct approach. Necessary for some games
# - Auto: DXVK will pick automatically
##############################
d3d9.forceSwapchainMSAA = 0
d3d9.supportVCache = False #Its only for Nvidia GPU (vcache query)
d3d9.forceSamplerTypeSpecConstants = False
dxvk.useRawSsbo = False # PLEASE NOT ENABLE IT, CAUSE LAGGY SHUTTERS
d3d9.textureMemory = 100 # The value in 100 mb = is default, but for old APU like Intel(R) HD Graphics 620, try test 25 mb or 50 mb


######## OPTIONAL SETTINGS, remove # for test
# For idiots games, it normaly by me should be true all
d3d9.supportD32 = False
d3d9.useD32forD24 = False

d3d9.supportX4R4G4B4 = False # CAUSE LAG AND LESS FPS GAIN. please dont ENABLE IT in Wow3.3.5a
d3d9.disableA8RT = True # improvement the login fast charging and other things very GOOD in TRUE
#########

# testing, if you have wow crash, delete the next line:
dxvk.gplAsyncCache=True # delete it if you getting crashes

#Explains:
# Some games think we are on Intel given a lack of NVAPI or
# AGS/atiadlxx support. Report our device memory as shared memory,
# and some small amount for a "carveout".
# Supported values: True, False

# dxgi.emulateUMA = False # IT says the game that we are using iGPU not NVAPI
